# Generated by Django 2.2.2 on 2019-07-29 15:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, default=None, null=True)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('num_guests', models.IntegerField(blank=True, null=True)),
                ('num_rooms', models.IntegerField(blank=True, null=True)),
                ('time_booked', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=10000000000, null=True)),
                ('free_parking', models.BooleanField(blank=True, default=False, null=True)),
                ('pool', models.BooleanField(blank=True, default=False, null=True)),
                ('gym', models.BooleanField(blank=True, default=False, null=True)),
                ('spa', models.BooleanField(blank=True, default=False, null=True)),
                ('ramp', models.BooleanField(blank=True, default=False, null=True)),
                ('travelator', models.BooleanField(blank=True, default=False, null=True)),
                ('elevator', models.BooleanField(blank=True, default=False, null=True)),
                ('apartment', models.BooleanField(blank=True, default=False, null=True)),
                ('hotel', models.BooleanField(blank=True, default=False, null=True)),
                ('house', models.BooleanField(blank=True, default=False, null=True)),
                ('resort', models.BooleanField(blank=True, default=False, null=True)),
                ('townhouse', models.BooleanField(blank=True, default=False, null=True)),
                ('kitchen', models.BooleanField(blank=True, default=False, null=True)),
                ('airconditioning', models.BooleanField(blank=True, default=False, null=True)),
                ('bathroom', models.BooleanField(blank=True, default=False, null=True)),
                ('tv', models.BooleanField(blank=True, default=False, null=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dashboard')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Property_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=10000000000)),
                ('rating', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Property')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.image_directory_path)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dashboard')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Property')),
            ],
        ),
    ]
