# Generated by Django 2.2.2 on 2019-07-29 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='display_image',
        ),
    ]
