# Generated by Django 2.2.2 on 2019-08-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='laundry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
