# Generated by Django 2.2.2 on 2019-07-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='dashboard_id',
            new_name='dashboard',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='property_id',
            new_name='property',
        ),
    ]
