# Generated by Django 2.2.2 on 2019-07-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
    ]
