# Generated by Django 2.2.2 on 2019-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190710_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
