# Generated by Django 2.2.2 on 2019-07-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190721_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='num_bookings',
            new_name='_time_booked',
        ),
    ]
