# Generated by Django 2.2.2 on 2019-08-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190801_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_review',
            name='cleanliness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property_review',
            name='communication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property_review',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property_review',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
