# Generated by Django 2.2.2 on 2019-07-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190721_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='_time_booked',
            new_name='time_booked',
        ),
    ]
