# Generated by Django 2.2.2 on 2019-08-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190802_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
