# Generated by Django 2.2.2 on 2019-08-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190804_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100000)),
                ('url_image', models.CharField(max_length=100000)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
