# Generated by Django 2.2.2 on 2019-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190725_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='free_parking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gym',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='spa',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
