# Generated by Django 2.2.2 on 2019-07-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190725_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='airconditioning',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tv',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
